"""initial schema

Revision ID: b9a9d8e464b3
Revisão anterior: 
Data de criação: 2026-06-19 04:27:52.670693+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Importa o tipo GUID customizado usado pelos models. Sem isto, a migration
# falha com NameError: name 'server' is not defined (autogenerate referencia
# o tipo pelo path completo mas não adiciona o import automaticamente).
from server.database.models import GUID


# Identificadores de revision
revision: str = 'b9a9d8e464b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federated_rooms',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('origin_room_id', GUID(), nullable=False),
    sa.Column('origin_server_domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('participating_servers', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_federated_rooms_origin_room_id'), 'federated_rooms', ['origin_room_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('rooms',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('server_peers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('trust_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_peers_domain'), 'server_peers', ['domain'], unique=True)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_expires_at'), 'users', ['expires_at'], unique=False)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_is_guest'), 'users', ['is_guest'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friendships',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('friend_id', GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('room_id', GUID(), nullable=False),
    sa.Column('sender_id', GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_prekeys',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_time_prekeys_used'), 'one_time_prekeys', ['used'], unique=False)
    op.create_index(op.f('ix_one_time_prekeys_user_id'), 'one_time_prekeys', ['user_id'], unique=False)
    op.create_table('private_messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('sender_id', GUID(), nullable=False),
    sa.Column('receiver_id', GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('federated_sender', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_private_messages_federated_sender'), 'private_messages', ['federated_sender'], unique=False)
    op.create_table('room_members',
    sa.Column('room_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('sessions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_table('user_identity_keys',
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('signed_prekey_pem', sa.Text(), nullable=False),
    sa.Column('signed_prekey_signature', sa.Text(), nullable=False),
    sa.Column('signed_prekey_rotated_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('attachments',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('uploader_id', GUID(), nullable=False),
    sa.Column('message_id', GUID(), nullable=True),
    sa.Column('private_message_id', GUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['private_message_id'], ['private_messages.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('user_identity_keys')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('room_members')
    op.drop_index(op.f('ix_private_messages_federated_sender'), table_name='private_messages')
    op.drop_table('private_messages')
    op.drop_index(op.f('ix_one_time_prekeys_user_id'), table_name='one_time_prekeys')
    op.drop_index(op.f('ix_one_time_prekeys_used'), table_name='one_time_prekeys')
    op.drop_table('one_time_prekeys')
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_guest'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_expires_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_server_peers_domain'), table_name='server_peers')
    op.drop_table('server_peers')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_federated_rooms_origin_room_id'), table_name='federated_rooms')
    op.drop_table('federated_rooms')
    # ### end Alembic commands ###
